### ISSUE TITLE
New NixOS wiki

### ISSUE THREAD

**Issue by Mic92** [rhasselbaum/nixos-config#1]
I saw your edit in the Raspberry Pi 4 article on nixos.wiki and just want to let you know that we also have https://wiki.nixos.org See https://github.com/NixOS/foundation/issues/113 for details.

**Comment by rhasselbaum** [comment]
Yeah, I discovered later there were two wikis and made the same edits in wiki.nixos.org. Unfortunately, Google seems to surface both of them.

**Comment by rhasselbaum** [comment]
Oh, and I just realized you are talking about a different (more recent) edit that I forgot to copy over. Thank you.

**Comment by Mic92** [comment]
Which wiki you find more trust worthy, is left as an exercise to the reader: https://nixos.wiki/wiki/Nixos_Woke_Invasion

**Comment by rhasselbaum** [comment]
Oh, I didn't realize I'd stumbled into a controversy. 😅 Thanks for letting
me know.
